### PR TITLE
Add Support for Engine Version

### PR DESCRIPTION
**Pull request by krkeegan**
Adds a get_engine command that can be used to get the engine
version which is saved in the device.db.

~~When refresh is called, if the engine version is not known,
it will be requested.~~

One step in process to fix https://github.com/TD22057/insteon-mqtt/issues/17

### CODE REVIEW

**Comment by krkeegan** [comment]
I removed the changes to the device refresh process, as discussed this won't work.  The remaining additions for supporting a get_engine request are good.  At least in the interim, I can manually call get_engine on devices I know to be i1

**Comment by TD22057** [comment]
Thanks for the contributions.  I'll make some time to integrate these but it's going to be a few weeks until I can get to them since I'm swamped at work with an upcoming delivery (and home with remodeling project) until the end of the month.  Just wanted to let you know that I'm not ignoring these...

**Comment by krkeegan** [comment]
No problem, I will try and compartmentalize everything but some improvements overlap with each other.

**Comment by TD22057** [comment]
Thanks.  I pushed a couple of minor tweaks and added a note in the release notes in HISTORY.md.

**Pull request merged**
